version: '3.8'

services:
  freqtrade:
    image: freqtradeorg/freqtrade:develop
    container_name: freqtrade
    restart: unless-stopped
    ports:
      - "8081:8080"  # Web UI
    volumes:
      - ./user_data:/freqtrade/user_data
      - ./config:/freqtrade/config
      - ./data:/freqtrade/data

    environment:
      - FT_CONFIG_PATH=/freqtrade/config/config.json
    # depends_on:
    #   - postgres
    command: >
      trade
      --config /freqtrade/config/config.json
      --strategy UltraDynamicStrategy_1753139562
      --db-url sqlite:///data/tradesv3_ultra_creative_strategy_final.db

 