version: '3.8'

services:
  freqtrade:
    image: freqtradeorg/freqtrade:develop
    container_name: freqtrade
    restart: unless-stopped
    ports:
      - "8080:8080"  # Web UI
    volumes:
      - ./user_data:/freqtrade/user_data
      - ./config:/freqtrade/config
    environment:
      - FT_CONFIG_PATH=/freqtrade/config/config.json
    # depends_on:
    #   - postgres
    command: >
      trade
      --config /freqtrade/config/config.json
      --strategy UltraCreativeStrategy_20250721_210729_iter_2
      --db-url sqlite:///tradesv3_ultra_creative_strategy_20250721_210729_iter_2.db

 